services:
  db:
    build: db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=mydb
    volumes:
      - ./db/src:/work

  web:
    build: web
    ports:
      - 9980:80
    volumes:
      - ./web/src:/var/www/html
