services:
  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mini
      - MYSQL_PASSWORD=shop
      - MYSQL_DATABASE=minishop
    volumes:
      - ./db/src:/work

  web:
    build: web
    ports:
      - 8080:80
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      - db
