services:
  db:
    container_name: mysql-db
    build: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mini
      - MYSQL_PASSWORD=shop
      - MYSQL_DATABASE=minishop
    volumes:
      - ./db/src:/work
    networks:
      - hoge0

  web:
    container_name: webserver
    build: web
    ports:
      - 8080:80
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      - db
    networks:
      - hoge0

networks:
  hoge0:
    driver: bridge
