services:
  db:
    container_name: mysql-db
    build: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=test1
    volumes:
      - ./db/src:/work

  web:
    container_name: webserver
    build: web
    ports:
      - 8080:80
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      - db
